# SPDX-License-Identifier: Apache-2.0
"""The Python tests must not touch the developer's real machine state.

The repo-root ``conftest.py`` pins ``FACTLOG_ROOT`` and ``XDG_CONFIG_HOME`` to
throwaway dirs. These assert that the pins are actually in force, because the
damage is silent: a test that shells out to ``factlog init`` writes the
active-KB config wherever ``XDG_CONFIG_HOME`` points, and if that is the real
``~/.config`` the developer's install ends up aimed at a pytest temp dir that
no longer exists. Nothing fails, and they find out the next time they run
``factlog``.

Asserting the *environment* rather than the writing test's behaviour is
deliberate: it holds no matter which test shells out, including ones added
later, and — via the subprocess probe below — including ones added outside
``tests/unit/``. Every ``tests/*.sh`` harness isolates this per-harness (see
the ``#62`` comments); the Python layer is the one that was missing it.
"""
from __future__ import annotations

import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

_REPO = Path(__file__).resolve().parents[2]


def _is_under(child: str, parent: Path) -> bool:
    try:
        Path(child).resolve().relative_to(parent.resolve())
    except ValueError:
        return False
    return True


def test_config_home_is_pinned():
    """Only ``XDG_CONFIG_HOME``: an existence check says nothing about FACTLOG_ROOT.

    Six tool modules (``tools/coverage.py``, ``ask_router.py``, ``entity_audit.py``,
    ``merge_candidates.py``, ``check_conflicts.py``, ``corroboration.py``) assign
    ``os.environ["FACTLOG_ROOT"]`` at import time, so in a full run the variable is
    set whether or not anything pinned it — measured: with this conftest deleted and
    the variable unset, an existence check on it still passes. What FACTLOG_ROOT
    needs is a check of its *value*, which is
    ``test_factlog_root_is_an_empty_throwaway_dir`` below.
    """
    assert os.environ.get("XDG_CONFIG_HOME"), (
        "XDG_CONFIG_HOME must be pinned by conftest before any tool import"
    )


def test_config_home_is_not_the_real_one():
    assert not _is_under(os.environ["XDG_CONFIG_HOME"], Path.home() / ".config"), (
        "XDG_CONFIG_HOME resolves inside the real ~/.config — a test that runs "
        "`factlog init` would overwrite the developer's active-KB config"
    )


def test_resolved_config_path_is_not_the_real_one():
    """The env var is the mechanism; this pins the thing that actually matters."""
    import factlog_config

    assert not _is_under(str(factlog_config.config_path()), Path.home() / ".config")


def test_config_home_is_a_throwaway_dir_made_for_this_run():
    """Not merely "a path that looks isolated" — one this run created.

    The two assertions above only see *where* ``XDG_CONFIG_HOME`` points, so
    they hold for any path outside ``~/.config`` — including a developer's real
    config at ``~/.dotfiles/config`` or ``~/Library/Application Support``.
    Pointing the variable somewhere non-default is its normal use, not an
    isolation signal, so what actually has to hold is that conftest overwrote
    whatever was inherited.
    """
    config_home = Path(os.environ["XDG_CONFIG_HOME"])
    assert config_home.name.startswith("factlog-tests-cfg-"), (
        f"XDG_CONFIG_HOME was inherited rather than pinned by conftest: {config_home} "
        "— an inherited path may be the developer's real config under a custom prefix"
    )
    assert _is_under(str(config_home), Path(tempfile.gettempdir()))


def test_factlog_root_is_an_empty_throwaway_dir():
    """A directory with nothing in it, not merely one without a ``facts/`` yet.

    ``FACTLOG_ROOT`` deliberately defers to an inherited value, so this cannot
    check for a temp-dir prefix — the value is checked instead. "No ``facts/``"
    was too weak on both ends: a KB whose facts have not been compiled yet
    passed, and so did the repo root itself, which is what the tool modules
    resolve to when nothing is pinned.
    """
    root = Path(os.environ["FACTLOG_ROOT"])
    assert root.is_dir(), f"FACTLOG_ROOT is not a directory: {root}"
    leftovers = sorted(p.name for p in root.iterdir())
    assert not leftovers, f"FACTLOG_ROOT points at a directory with contents: {root} {leftovers}"


_PROBE = '''\
# SPDX-License-Identifier: Apache-2.0
"""Generated by test_pins_cover_tests_outside_the_unit_dir; not collected by
`pytest` on its own (testpaths = tests/unit)."""
import os
from pathlib import Path


def test_config_home_is_pinned_here_too():
    config_home = os.environ.get("XDG_CONFIG_HOME")
    assert config_home, "XDG_CONFIG_HOME is unpinned outside tests/unit"
    real = (Path.home() / ".config").resolve()
    resolved = Path(config_home).resolve()
    assert resolved != real and real not in resolved.parents, (
        f"XDG_CONFIG_HOME resolves inside the real ~/.config: {config_home}"
    )
'''


def test_pins_cover_tests_outside_the_unit_dir(tmp_path):
    """The pins belong to the repo root, not to ``tests/unit/``.

    While they lived in ``tests/unit/conftest.py``, a Python test added
    anywhere else got no protection at all and ``pytest tests/`` would clobber
    the developer's active-KB config while reporting all green. This drops a
    throwaway test outside ``tests/unit/`` and runs it in a child pytest with a
    fake ``HOME`` and no inherited ``XDG_CONFIG_HOME``, so only the repo-root
    conftest can satisfy it.
    """
    probe_dir = Path(tempfile.mkdtemp(dir=_REPO / "tests", prefix="pin_probe_"))
    home = tmp_path / "home"
    (home / ".config").mkdir(parents=True)
    try:
        (probe_dir / "test_probe.py").write_text(_PROBE, encoding="utf-8")
        env = {k: v for k, v in os.environ.items() if k != "XDG_CONFIG_HOME"}
        env["HOME"] = str(home)
        proc = subprocess.run(
            [sys.executable, "-m", "pytest", str(probe_dir), "-q", "-p", "no:cacheprovider"],
            cwd=_REPO, capture_output=True, text=True, env=env,
        )
    finally:
        shutil.rmtree(probe_dir, ignore_errors=True)
    assert proc.returncode == 0, proc.stdout + proc.stderr
